services:
  db:
    container_name: relis-db
    image: mariadb:11.4
    restart: always
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"

    command: mariadbd --general-log=1 --general-log-file=/var/log/mysql/general.log --slow-query-log=1 --slow-query-log-file=/var/log/mysql/slow.log --log-output=FILE --log-error=/var/log/mysql/error.log

    volumes:
      - ./db/initial_db.sql:/docker-entrypoint-initdb.d/initial_db.sql
      - ../data/db:/var/lib/mysql
      - ../logs/db:/var/log/mysql

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    volumes:
      - ./db/config.inc.php:/etc/phpmyadmin/config.inc.php
      - ../:/u/relis/public_html

  tomcat:
    depends_on:
      - db
    build:
      context: ./tomcat/
    volumes:
      - ../data/tomcat_data:/u/relis/public_html/workspace
    environment:
      MYSQL_DATABASE: db
      CATALINA_OPTS: '-Xms512M -Xmx1024M -server -XX:+UseParallelGC'
      JAVA_OPTS: '-Djava.security.egd=file:///dev/urandom'
    ports:
      - 8088:8080
      - 8089:8181

  bibler:
    container_name: bibler
    image: relis/bibler
    restart: always

  relis-application:
    depends_on:
      - db
    container_name: relis-app
    build:
      context: ./
      args:
        DIRECTORY_INDEX: index.php
        DOCUMENT_ROOT: /u/relis/public_html
        ENV: dev
    entrypoint: /usr/local/bin/entrypoint.sh
    ports:
      - 8083:80
    volumes:
      - ../:/u/relis/public_html
    extra_hosts:
      - "host.docker.internal:host-gateway"
