services:
  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - relis-application
      - tomcat
      - bibler

  db:
    image: mariadb:11.4
    restart: always
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"

    deploy:
      replicas: 1

      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    command: mariadbd --general-log=1 --general-log-file=/var/log/mysql/general.log --slow-query-log=1 --slow-query-log-file=/var/log/mysql/slow.log --log-output=FILE --log-error=/var/log/mysql/error.log

    volumes:
      - ./db/initial_db.sql:/docker-entrypoint-initdb.d/initial_db.sql
      - ../data/db:/var/lib/mysql
      - ../logs/db:/var/log/mysql

  tomcat:
    depends_on:
      - db
    build:
      context: ./tomcat/
    volumes:
      - ../data/tomcat_data:/u/relis/public_html/workspace #TODO: Document if we need to change host path or not
    networks:
      default:
        aliases:
          - relistomcat
    deploy:
      replicas: 1

      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    environment:
      MYSQL_DATABASE: db
      CATALINA_OPTS: '-Xms512M -Xmx1024M -server -XX:+UseParallelGC'
      JAVA_OPTS: '-Djava.security.egd=file:///dev/urandom'

  bibler:
    image: relis/bibler:latest
    restart: always
    environment:
      ENV: "prod"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

  relis-application:
    depends_on:
      - db
    build:
      context: ./
      args:
        - DOCUMENT_ROOT=/u/relis/public_html
        - DIRECTORY_INDEX=index.php
        - ENV=prod
    env_file:
      - .env
    entrypoint: /usr/local/bin/entrypoint.sh
    restart: always
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    volumes:
      - ../:/u/relis/public_html
